In [4]:
import numpy as np
from Randomization_Function import Pathway_Randomization


#Toy Matrix
original_matrix = np.array([
    [1, 0, 1, 1, 1, 0],
    [0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0],
    [0, 1, 0, 1, 0, 0],
    [0, 0, 1, 1, 1, 1],
    [0, 0, 0, 1, 0, 1]
])

# Example Matrix (256x256)
# file_path = "Data/example_matrix.npy"
# original_matrix = np.load(file_path)

In [5]:
# Shuffling with various modes

# mode = 'column' to keep the number of ones in each column constant
reshuffled_column = Pathway_Randomization(original_matrix, mode = 'column', seed = 42)

# mode = 'row' to keep the number of ones in each row constant
reshuffled_row = Pathway_Randomization(original_matrix, mode = 'row', seed = 42)

# mode = 'global' to keep the total number of ones constant
reshuffled_global = Pathway_Randomization(original_matrix, mode = 'global', seed = 42)

# mode = 'sparsity' and sparsity = threshold to set the total number of ones based on the desired sparsity
reshuffled_sparsity = Pathway_Randomization(original_matrix, mode = 'sparsity', sparsity = 0.7, seed = 42)


In [6]:
def print_ones_count(matrix, label):
    print(f"{label}:")
    print(matrix)
    print(f"Number of ones per row: {np.sum(matrix, axis = 1)}")
    print(f"Number of ones per column: {np.sum(matrix, axis = 0)}")
    print(f"Global number of ones: {np.sum(matrix)}")
    print()
    
# Checking the number of ones in each row, column and globally in the shuffled matrices
print_ones_count(original_matrix, "Original")
print_ones_count(reshuffled_column, "Column-wise constant")
print_ones_count(reshuffled_row, "Row-wise constant")
print_ones_count(reshuffled_global, "Global constant")
print_ones_count(reshuffled_sparsity, "70% Sparsity")

Original:
[[1 0 1 1 1 0]
 [0 1 0 0 0 0]
 [1 0 0 1 0 0]
 [0 1 0 1 0 0]
 [0 0 1 1 1 1]
 [0 0 0 1 0 1]]
Number of ones per row: [4 1 2 2 4 2]
Number of ones per column: [2 2 2 5 2 2]
Global number of ones: 15

Column-wise constant:
[[1 0 0 1 0 1]
 [0 1 0 1 1 0]
 [1 1 0 1 0 0]
 [0 0 1 0 0 1]
 [0 0 1 1 0 0]
 [0 0 0 1 1 0]]
Number of ones per row: [3 3 3 2 2 2]
Number of ones per column: [2 2 2 5 2 2]
Global number of ones: 15

Row-wise constant:
[[1 0 1 1 0 1]
 [0 0 0 1 0 0]
 [0 0 0 1 1 0]
 [0 1 0 0 0 1]
 [1 1 1 0 1 0]
 [1 0 0 0 1 0]]
Number of ones per row: [4 1 2 2 4 2]
Number of ones per column: [3 2 2 3 3 2]
Global number of ones: 15

Global constant:
[[1 0 0 0 1 0]
 [0 0 1 1 0 0]
 [1 1 0 0 1 1]
 [0 0 0 1 0 0]
 [0 0 1 0 0 1]
 [1 1 0 0 1 1]]
Number of ones per row: [2 2 4 1 2 4]
Number of ones per column: [3 2 2 2 3 3]
Global number of ones: 15

70% Sparsity:
[[0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [1 1 0 0 1 1]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [1 1 0 0 0 1]]
Number of ones per row: [0 1 4 1 1 3]
N